import os
import subprocess
def main():
    os.system("figlet show tools")
    print("1.Install BeEf")
    print("###############")
    print("2.Install Kali Nethunter")
    print("#########################")
    print("3.Install Metasploit")
    print("###############")
    print("4.install Nmap")
    print("###############")
    print("5.Install Sqlmap")
    print("#################")
    print("6.Install DarkFly-Tool")
    print("#######################")
    print("7.Install Lazymux")
    print("#################")
    print("8.Install Ghost-Droid")
    print("#####################")
    print("9.Install Phoneinfoga")
    print("######################")
    print("10.Install Userrecon")
    print("#####################")
    print("11.Install Report")
    print("##################")
    print("12.Install Instagram")
    print("#####################")
    print("13.Install Instagram-Tool")
    print("#########################")
    print("14.Install Hacktronian")
    print("#######################")
    print("15.Install Weeman")
    print("#################")
    print("16.Install Tmuxbunch")
    print("####################")
    print("17.Install IP-Tracer")
    print("#####################")
    print("18.Install Shellphish")
    print("#####################")
    print("19.Install Brutescrape")
    print("######################")
    print("20.Red_Hawk")
    print("#########")
    print("21.blackeye")
    print("############")
    print("22.seeker")
    print("##########")
    print("23.saycheese")
    print("###########")
    print("24.HiddenEye")
    print("###############")
    print("00.Back")
    print("########")
    a = int(input("choose:-"))
    if a==1:
         os.system("cd tool && ./beef.sh")
    elif a==2:
        os.system("cd tool && ./kali")
    elif a==3:
        os.system("apt-get update -y ")
        os.system("apt-get upgrade -y")
        os.system("apt-get install python -y")
        os.system("apt-get install curl -y")
        os.system("apt-get install git -y")
        os.system("apt-get install python2 -y")
        os.system("pkg install unstable-repo -y")
        os.system("pkg install metasploit -y")
    elif a==4:
        os.system("apt-get update -y ")
        os.system("apt-get upgrade -y")
        os.system("apt-get install python -y")
        os.system("apt-get install curl -y")
        os.system("apt-get install git -y")
        os.system("apt-get install python2 -y")
        os.system("apt install nmap")
        os.system("mv nmap /data/data/com.termux/files/home")
    elif a==5:
        os.system("apt-get update -y ")
        os.system("apt-get upgrade -y")
        os.system("apt-get install python -y")
        os.system("apt-get install curl -y")
        os.system("apt-get install git -y")
        os.system("apt-get install python2 -y")
        os.system("git clone https://github.com/sqlmapproject/sqlmap.git")
        os.system("mv sqlmap /data/data/com.termux/files/home")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd sqlmap && chmod +x * && python2 sqlmap.py")
    elif a==6:
        os.system("apt-get update -y ")
        os.system("apt-get upgrade -y")
        os.system("apt-get install python -y")
        os.system("apt-get install curl -y")
        os.system("apt-get install git -y")
        os.system("apt-get install python2 -y")
        os.system("git clone https://github.com/Ranginang67/DarkFly-Tool")
        os.system("mv DarkFly-Tool /data/data/com.termux/files/home")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd DarkFly-Tool && chmod +x * && python2 install.py")
    elif a==7:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("git clone https://github.com/Gameye98/Lazymux.git")
         os.system("mv lazymux /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd lazymux && chmod +x * && python2 lazymux.py")
    elif a==8:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("git clone https://github.com/GhosTmaNHarsh/Ghost-Droid.git")
         os.system("mv Ghost-Droid /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd Ghost-Droid && chmod +x * && ./setup && ./ghost-droid")
    elif a==9:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("git clone https://github.com/sundowndev/PhoneInfoga")
         os.system("mv PhoneInfoga /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd PhoneInfoga && pip3 install -r requirements.txt")
    elif a==10:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("git clone https://github.com/thelinuxchoice/userrecon.git")
         os.system("mv userrecon /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd userrecon && chmod +x userrecon.sh && ./userrecon.sh")
    elif a==11:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("git clone https://github.com/IlayTamvan/Report")
         os.system("mv Report /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd Report &&  unzip Report.zip && python2 Report.py")
    elif a==12:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("git clone https://github.com/HackerUniverse/Instagram")
         os.system("mv Instagram /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd Instagram && chmod +x * && pip install -r requirements.txt && python2 instagram.py")
    elif a==13:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("git clone https://github.com/masokky/instagram-tools.git")
         os.system("mv instagram-tools /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd instagram-tools && node index.js")
    elif a==14:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("git clone https://github.com/thehackingsage/hacktronian.git")
         os.system("mv hacktronian /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd hacktronian && chmod +x hacktronian.py && python2 hacktonian.py")
    elif a==15:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("git clone https://github.com/evait-security/weeman.git")
         os.system("mv weeman /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd weeman && chmod +x weeman.py && python2 weeman.py")
    elif a==16:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("apt-get install axel -y")
         os.system("axel https://github.com/Hax4us/Tmux-Bunch/releases/download/v2.7/Tmux-Bunch-2.7.tar.gz")
         os.system("tar -xf Tmux-Bunch-2.7.tar.gz")
         os.system("mv Tmux-Bunch /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd Tmux-Bunch && chmod +x * && bash setup && ./tmuxbunch")
    elif a==17:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("apt-get install axel -y")
         os.system("git clone https://github.com/Rajkumrdusad/IP-Tracer.git")
         os.system("mv IP-Tracer /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd IP-Tracer && chmod +x install && ./install")
    elif a==18:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("apt-get install php -y")
         os.system("git clone https://github.com/thelinuxchoice/shellphish.git")
         os.system("mv shellphish /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd shellphish && chmod +x * && bash shellphish.sh")
    elif a==19:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("apt-get install php -y")
         os.system("git clone https://github.com/Rajkumrdusad/IP-Tracer.git")
         os.system("mv IP-Tracer /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd IP-Tracer && chmod +x install && ./install")
    elif a==20:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("apt-get install php -y")
         os.system("git clone https://github.com/Tuhinshubhra/RED_HAWK.git")
         os.system("mv IP-Tracer /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd RED_HAWK && chmod +x rhawk.php && php rhawk.php")
    elif a==21:
         os.system("apt-get update -y ")
         os.system("apt-get upgrade -y")
         os.system("apt-get install python -y")
         os.system("apt-get install curl -y")
         os.system("apt-get install git -y")
         os.system("apt-get install python2 -y")
         os.system("apt-get install php -y")
         os.system("git clone https://github.com/thelinuxchoice/blackeye")
         os.system("mv blackeye /data/data/com.termux/files/home")
         print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd blackeye && bash blackeye.sh")
    elif a==22:
        os.system("apt-get update -y ")
        os.system("apt-get upgrade -y")
        os.system("apt-get install python -y")
        os.system("apt-get install curl -y")
        os.system("apt-get install git -y")
        os.system("apt-get install python2 -y")
        os.system("apt-get install php -y")
        os.system("git clone https://github.com/thewhiteh4t/seeker.git")
        os.system("mv seeker /data/data/com.termux/files/home")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd seeker && chmod 777 termux_install.sh && ./termux_install.sh")
    elif a==23:
        os.system("apt-get update -y ")
        os.system("apt-get upgrade -y")
        os.system("apt-get install python -y")
        os.system("apt-get install curl -y")
        os.system("apt-get install git -y")
        os.system("apt-get install python2 -y")
        os.system("apt-get install php -y")
        os.system("git clone https://github.com/thelinuxchoice/saycheese.git")
        os.system("mv saycheese /data/data/com.termux/files/home")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd saycheese && bash saycheese.sh")
    elif a==24:
        os.system("apt-get update -y ")
        os.system("apt-get upgrade -y")
        os.system("apt-get install python -y")
        os.system("apt-get install curl -y")
        os.system("apt-get install git -y")
        os.system("apt-get install python2 -y")
        os.system("apt-get install php -y")
        os.system("git clone git clone -b Termux-Support-Branch https://github.com/DarkSecDevelopers/HiddenEye.git")
        os.system("mv HiddenEye /data/data/com.termux/files/home")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd HiddenEye && chmod 777 HiddenEye.py && python3 HiddenEye.py")
    elif a==00:
         os.system("./hacker-tool")
    else:
         print("invalid input")
def hack():
    os.system("figlet spam tools")
    print("1.spamerCALL")
    print("############")
    print("2.spammer")
    print("#########")
    print("3.TBomb")
    print("#######")
    print("4.Spammer-Grab")
    print("###############")
    print("5.SpazSMS")
    print("#########")
    print("6.LITEOTP")
    print("##########")
    print("7.Back")
    print("######")
    b=int(input("choose:-"))
    if b==1:
        os.system("cd tool && ./call")
    elif b==2:
        os.system("cd tool && ./calling")
    elif b==3:
        os.system("git clone https://github.com/TheSpeedX/TBomb.git")
        os.system("mv TBomb /data/data/com.termux/files/home")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd TBomb && chmod +x TBomb.sh && ./TBomb.sh")
    elif b==4:
        os.system("git clone https://github.com/Noxturnix/Spammer-Grab")
        os.system("mv Spammer-Grab /data/data/com.termux/files/home")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd Spammer-Grab && ./auto-install.sh")
    elif b==5:
        os.system("git clone https://github.com/Gameye98/SpazSMS")
        os.system("mv SpazSMS /data/data/com.termux/files/home")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd SpazSMS && chmod +x * && python2 lite.py")
    elif b==6:
        os.system("apt install php php-curl wget $ wget https://raw.githubusercontent.com/Cvar1984/LiteOTP/master/build/main.phar -O $PREFIX/bin/lite  ")
        os.system("mv LITEOTP /data/data/com.termux/files/home")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n chmod +x $PREFIX/bin/lite && lite /foo/bar/test_list.txt")
    elif b==7:
        os.system("./hacker-tool")
    else:
        print("invalid input")
def a():
    print("1.kali linux")
    print("2.ubuntu")
    print("00.Back")
    c=int(input("choose:-"))
    if c==1:
        os.system("cd tool && ./kalilinux")
    elif c==2:
        os.system("pkg install wget proot")
        os.system("git clone https://github.com/Neo-Oli/termux-ubuntu.git")
        print("GO TO TERMUX HOME DIRECTORY AND PASTE THE COMMANDS \n cd termux-ubuntu && sh ubuntu.sh && ./start.sh")
    elif c==00:
        os.system("./hacker-tool")
    else:
        print("invalid input")
while(1):
    print("1.show tools")
    print("#############")
    print("2.spam tools")
    print("#############")
    print("3.os")
    print("####")
    print("4.install usefull pkg")
    print("######################")
    print("5.exit")
    print("#######")
    d=int(input("choose:-"))
    if d==1:
        main()
    elif d==2:
        hack()
    elif d==3:
        a()
    elif d==4:
        os.system("apt-get update -y ")
        os.system("apt-get upgrade -y")
        os.system("apt-get install python -y")
        os.system("apt-get install curl -y")
        os.system("apt-get install git -y")
        os.system("apt-get install python2 -y")
        os.system("apt-get install php -y")
        os.system("apt-get install lolcat -y")
        os.system("apt-get install figlet -y")
        os.system("apt-get install wget -y")
        os.system("apt-get install axel -y")
    elif d==5:
        print("THANKS FOR USING THIS TOOL , BYE......")
        break
    else:
        print("INVALID INPUT")
        os.system("./hacker-tool")
        continue
