#!/data/data/com.termux/files/usr/bin/bash
clear
figlet Hacker-Tool |lolcat
echo "Author - Aditya" |lolcat
echo "################" |lolcat
echo "github - https://github.com/TechnicalDangwal" |lolcat
echo "##########################################" |lolcat
echo "My Youtube channel - Technical Dangwal" |lolcat
echo "#####################################" |lolcat
echo "DON'T FORGOT TO SUBCRIBE MY YOUTUBE CHANNEL" |lolcat
echo "############################################" |lolcat
echo "Do not copy or try to modify the codes" |lolcat
echo "######################################" |lolcat
echo ""
echo "########################################"
echo "---------------LIST TOOLS-------------"
echo "########################################"
echo ""
echo ""
python hacker-tool.py |lolcat

